import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`dark ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <script src="https://cdn.tailwindcss.com?plugins=forms,container-queries"></script>
        <link href="https://fonts.googleapis.com/css2?family=Hanken+Grotesk:wght@400;500;600;700&amp;family=JetBrains+Mono:wght@400;500;700&amp;family=Sora:wght@400;600;700;800&amp;display=swap" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&amp;display=swap" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&amp;display=swap" rel="stylesheet"/>
        <script id="tailwind-config" dangerouslySetInnerHTML={{__html: `
        tailwind.config = {
          darkMode: "class",
          theme: {
            extend: {
              "colors": {
                      "critical-red": "#EF4444",
                      "on-tertiary": "#502400",
                      "on-primary": "#002e6a",
                      "error": "#ffb4ab",
                      "on-secondary-fixed": "#23005c",
                      "inverse-primary": "#005ac2",
                      "primary-container": "#4d8eff",
                      "surface-glass": "rgba(30, 41, 59, 0.5)",
                      "inverse-surface": "#dae2fd",
                      "surface-bright": "#31394d",
                      "on-secondary-fixed-variant": "#5516be",
                      "tertiary-fixed-dim": "#ffb786",
                      "on-error": "#690005",
                      "on-error-container": "#ffdad6",
                      "on-tertiary-fixed": "#311400",
                      "surface-container-lowest": "#060e20",
                      "surface-container": "#171f33",
                      "secondary-fixed": "#e9ddff",
                      "on-tertiary-container": "#461f00",
                      "primary": "#adc6ff",
                      "surface-container-high": "#222a3d",
                      "surface-dim": "#0b1326",
                      "on-tertiary-fixed-variant": "#723600",
                      "primary-fixed": "#d8e2ff",
                      "secondary": "#d0bcff",
                      "on-secondary-container": "#c4abff",
                      "tertiary-fixed": "#ffdcc6",
                      "tertiary-container": "#df7412",
                      "background": "#0b1326",
                      "surface-tint": "#adc6ff",
                      "border-glow": "rgba(139, 92, 246, 0.3)",
                      "secondary-container": "#571bc1",
                      "on-primary-fixed-variant": "#004395",
                      "success-emerald": "#10B981",
                      "error-container": "#93000a",
                      "on-secondary": "#3c0091",
                      "on-surface": "#dae2fd",
                      "inverse-on-surface": "#283044",
                      "on-background": "#dae2fd",
                      "on-primary-container": "#00285d",
                      "warning-amber": "#F59E0B",
                      "outline-variant": "#424754",
                      "outline": "#8c909f",
                      "surface-container-highest": "#2d3449",
                      "surface-variant": "#2d3449",
                      "on-primary-fixed": "#001a42",
                      "surface-container-low": "#131b2e",
                      "tertiary": "#ffb786",
                      "on-surface-variant": "#c2c6d6",
                      "surface": "#0b1326",
                      "primary-fixed-dim": "#adc6ff",
                      "secondary-fixed-dim": "#d0bcff"
              },
              "borderRadius": {
                      "DEFAULT": "0.25rem",
                      "lg": "0.5rem",
                      "xl": "0.75rem",
                      "full": "9999px"
              },
              "spacing": {
                      "stack-md": "16px",
                      "stack-lg": "32px",
                      "gutter": "24px",
                      "container-max": "1280px",
                      "margin-mobile": "16px",
                      "stack-sm": "8px"
              },
              "fontFamily": {
                      "headline-lg": [
                              "Sora"
                      ],
                      "headline-lg-mobile": [
                              "Sora"
                      ],
                      "body-lg": [
                              "Hanken Grotesk"
                      ],
                      "headline-md": [
                              "Sora"
                      ],
                      "display-lg": [
                              "Sora"
                      ],
                      "label-caps": [
                              "JetBrains Mono"
                      ],
                      "body-md": [
                              "Hanken Grotesk"
                      ]
              },
              "fontSize": {
                      "headline-lg": [
                              "32px",
                              {
                                      "lineHeight": "40px",
                                      "fontWeight": "600"
                              }
                      ],
                      "headline-lg-mobile": [
                              "28px",
                              {
                                      "lineHeight": "36px",
                                      "fontWeight": "700"
                              }
                      ],
                      "body-lg": [
                              "18px",
                              {
                                      "lineHeight": "28px",
                                      "fontWeight": "400"
                              }
                      ],
                      "headline-md": [
                              "24px",
                              {
                                      "lineHeight": "32px",
                                      "fontWeight": "600"
                              }
                      ],
                      "display-lg": [
                              "48px",
                              {
                                      "lineHeight": "56px",
                                      "letterSpacing": "-0.02em",
                                      "fontWeight": "700"
                              }
                      ],
                      "label-caps": [
                              "12px",
                              {
                                      "lineHeight": "16px",
                                      "letterSpacing": "0.1em",
                                      "fontWeight": "500"
                              }
                      ],
                      "body-md": [
                              "16px",
                              {
                                      "lineHeight": "24px",
                                      "fontWeight": "400"
                              }
                      ]
              }
      },
          },
        }
    `}} />
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
